### ISSUE TITLE
Wishlist: button reload data for a already solved image from astrometry.net [solved]

### ISSUE THREAD

**Issue by apos** [RedburnM/WordpressAstrometry#5]
[nova_astrometry_net_joblog_4824414.txt](https://github.com/MattChique/WordpressAstrometry/files/5748117/nova_astrometry_net_joblog_4824414.txt)
[nova_astrometry_net_joblog_4823522.txt](https://github.com/MattChique/WordpressAstrometry/files/5748122/nova_astrometry_net_joblog_4823522.txt)

Hi,

**Situation:** 
The wordpress plugin successfully solves the image via astronomy.net and identifies correctly objects in the annotated image.

**Expected behaviour:**
The object NGC 7000 is part of the annotated image at astrometry.net and therefore 
1. should be part of the (machine_) tags-array of the image. 
2. should be part of the annotated image in the wordpress plugin - but is not.

See: 
1. https://nova.astrometry.net/user_images/4257623#annotated (NGC 7000) 
2. https://avvp.de/cygnus-wall-ngc7000  (now corrected the skyplot, due to the use of a new Astrometry-User and new solve)

**Errors:**
1. This (or probably something else) leads to the fact, that also the **Skyplot** is not shown correctly (not sure)?
2. The taglist is empty. Are the right tags (tags / machine_tags) used? Does the **taglist** correspond to the annotated view of the picture?
3. It is not possible to **manually reload data from astrometry** (you can manually add tags at their webpage)

**Tried solutions:**
So I tried to add the tag manually on astronomy.net, which is possible. BUT it is not possible to "reload" the values within the Block. This was not possible, even when deleting and recreating the block, restarting the server ....

**Possible solutions?:**
1. Create a "reload" checkbox, so that after the "solved" flag was set, the data from astronomy.net are reread again for the same picture.
2.  resolved the image with another user (API). The skyplot is loaded correctly, but the objectlist is empty as epected (not ok). Unfortunately you cannot (!) simply copy the Block from the newly created page to the old. "Something" in the background ties the author of the page an the used image together. You have to recreate the whole page with a new user. 
Here is the result: https://avvp.de/cygnus-wall-ngc7000/

I know the might be a special case but these special cases might help develop the plugin further. Probably I will find a way to dig deeper into the code :-)

Cheers and thanks for your work
Axel

**Comment by MattChique** [comment]
Ohhh,  I noticed the "Add Tag" feature just now. Some "Reload tags" button makes sense.




Your other problem seems to be an astrometry.net issue. Probably because the center of NGC7000 is outside the image. 

![image](https://user-images.githubusercontent.com/26269158/103298920-a80d6080-49fb-11eb-8de0-4c1d91f74f2b.png)

astrometry.net only returns HD stars (I have used your image for this test case):

`{"annotations": [{"type": "hd", "names": ["HD 199511"], "pixelx": 2550.231132264265, "pixely": 19.83753453082045, "radius": 0.0}, {"type": "hd", "names": ["HD 199580"], "pixelx": 3895.7340522802137, "pixely": 394.39436923110134, "radius": 0.0}, {"type": "hd", "names": ["HD 200178"], "pixelx": 2056.7576068356975, "pixely": 1999.7258907411247, "radius": 0.0}, {"type": "hd", "names": ["HD 200020"], "pixelx": 2787.8625749110197, "pixely": 1551.7971075672872, "radius": 0.0}, {"type": "hd", "names": ["HD 200103"], "pixelx": 3697.712148903938, "pixely": 1901.579409962048, "radius": 0.0}, {"type": "hd", "names": ["HD 200311"], "pixelx": 1615.11036476362, "pixely": 2322.2280226410003, "radius": 0.0}, {"type": "hd", "names": ["HD 199547"], "pixelx": 1315.2240369841563, "pixely": 40.257665025437745, "radius": 0.0}, {"type": "hd", "names": ["HD 200042"], "pixelx": 3370.400412665096, "pixely": 1662.010795892221, "radius": 0.0}, {"type": "hd", "names": ["HD 199956"], "pixelx": 822.614664909969, "pixely": 1181.9720890161293, "radius": 0.0}, {"type": "hd", "names": ["HD 200060"], "pixelx": 372.13150401634675, "pixely": 1449.5482279035132, "radius": 0.0}, {"type": "hd", "names": ["HD 200407"], "pixelx": 393.73131625525, "pixely": 2483.9807933589027, "radius": 0.0}, {"type": "hd", "names": ["HD 200509"], "pixelx": 470.9329959749639, "pixely": 2807.905961103183, "radius": 0.0}]}`

AND empty tags:

`{"tags": []}`

**Comment by apos** [comment]
Hi Matt, thanks for digging into the problem. 

I dig deeper into the API: https://buildmedia.readthedocs.org/media/pdf/astrometrynet/latest/astrometrynet.pdf. I am joining the **Astrometry GoogleGroups** https://groups.google.com/g/astrometry and ask, if someone can answer me the question, why on the astrometry page the NGC 7000 can be seen in the annotated image, whereas the data shows nothing ... we will see :-)

- see post : https://groups.google.com/g/astrometry/c/3s3X3xqiaNU


I can confirm your inspection upon the actual data: https://avvp.de/cygnus-wall-ngc7000 / Job-ID: 4824414 which is part of http://nova.astrometry.net/user_images/4258515 (made it publically visible for some time ...).

-  Added tag: http://nova.astrometry.net/api/jobs/4824414/tags 
`{"tags": ["NGC 7000"]}`
Which is "my" newly added tag :-) 

- Objects: http://nova.astrometry.net/api/jobs/4824414/objects_in_field
`{"objects_in_field": []}`

- Info: http://nova.astrometry.net/api/jobs/4824414/info (**with newly added custom tag**)
`{"objects_in_field": [], 
"machine_tags": [], 
"tags": ["NGC 7000"], 
"status": "success", 
"original_filename": "NGC7000_CygnusWall.jpg", 
"calibration": {"ra": 314.82869896032986, "dec": 43.57967708653983, "radius": 0.9351788646663579, "pixscale": 2.228047010699512, "orientation": 85.62908125229762, "parity": 1.0}}`

I will ask someone in google groups and give feedback. 
THX Axel

**Comment by apos** [comment]
Got an answer from Dustin @astrometry.net: https://groups.google.com/g/astrometry/c/3s3X3xqiaNU/m/PAG3bNEvBwAJ

New bug: https://github.com/dstndstn/astrometry.net/issues/207 

Stay tuned. 
Happy new year.

Cheers,
Axel

**Comment by MattChique** [comment]
![image](https://user-images.githubusercontent.com/26269158/103540547-28b7db00-4e9a-11eb-8665-0df493c3f949.png)

Axel here is your reload button :-) of course, visible only for admins

**Comment by apos** [comment]
Thank you so much! We will see how Dustin from astrometry will dig into the problem with objects "out of border".  But this is not a problem of you plugin and as a sideeffect we will profit of it.  Thanks to the relaod button this then should appear in the data (I hope). If not, reprocessing will be the way to go. 

Cheers
Axel
